---

include:
  - platal/compose.yaml
  - nas/compose.yaml
  # - salon-des-inventions/compose.yaml

services:
  traefik:
    image: traefik:v3.1
    restart: always
    environment:
      INFOMANIAK_ACCESS_TOKEN: ${INFOMANIAK_ACCESS_TOKEN}
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - ./config/traefik:/etc/traefik
      - ./data/traefik/acme/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

networks:
  web:
    external: true
