services:
  samba:
    image: dperson/samba
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_MEDIA}:/mount
    environment:
      - USERID=1000
      - GROUPID=1000
      # USER and PASSWORD set on the host there https://blog.kye.dev/proxmox-zfs-mounts
      - USER=${SMB_USER};${SMB_PASSWORD}
    ports:
      - "139:139"
      - "445:445"
    command: [ "-s", "media;/mount;yes;no;no;all;none", "-p" ]
