---

services:

  platalhomepage:
    image: nginx:alpine
    ports:
      - "${PLATAL_HOMEPAGE_PORT}:443"
    restart: unless-stopped
    volumes:
      - ./homepage/index.html:/usr/share/nginx/html/index.html
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.platalhomepage.rule=Host(`${PUBLIC_URL_PLATAL_HOMEPAGE}`)"
      - "traefik.http.routers.platalhomepage.entrypoints=websecure"
      - "traefik.http.routers.platalhomepage.tls.certresolver=myresolver"
      - "homepage.group=Platal"
      - "homepage.name=platal.ch"
      - "homepage.icon=mdi-home"
      - "homepage.href=https://${PUBLIC_URL_PLATAL_HOMEPAGE}"
      - "homepage.description=Main homelab dashboard"

  bisou:
    image: nginx:alpine
    ports:
      - "16969:443"
    restart: unless-stopped
    volumes:
      - ./bisou/index.html:/usr/share/nginx/html/index.html
      - ./bisou/message.mp3:/usr/share/nginx/html/message.mp3
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.bisou.rule=Host(`bisou.thvi.ch`)"
      - "traefik.http.routers.bisou.entrypoints=websecure"
      - "traefik.http.routers.bisou.tls.certResolver=myresolver"

  vikunja:
    image: vikunja/vikunja
    ports:
      - "${VIKUNJA_PORT}:3456"
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://${PUBLIC_URL_VIKUNJA}
      VIKUNJA_DATABASE_HOST: vikunja_db
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_MYSQL_PASSWORD}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
    volumes:
      - .../data/vikunja/files:/app/vikunja/files
    networks:
      - web
      - default
    depends_on:
      vikunja_db:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.vikunja.rule=Host(`${PUBLIC_URL_VIKUNJA}`)"
      - "traefik.http.routers.vikunja.entrypoints=websecure"
      - "traefik.http.routers.vikunja.tls.certResolver=myresolver"
      - "homepage.group=Platal"
      - "homepage.name=Vikunja"
      - "homepage.icon=mdi-check"
      - "homepage.href=https://${PUBLIC_URL_VIKUNJA}"
      - "homepage.description=Task manager"
      - "homepage.widget.type=vikunja"
      - "homepage.widget.url=https://${PUBLIC_URL_VIKUNJA}"
      - "homepage.widget.key=${VIKUNJA_API_KEY}"
      - "homepage.widget.enableTaskList=true"

  vikunja_db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${VIKUNJA_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: ${VIKUNJA_MYSQL_PASSWORD}
      MYSQL_DATABASE: vikunja
    volumes:
      - ../data/vikunja/db:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD" ]
      interval: 2s
      start_period: 30s
  # leantime:
  #   image: leantime/leantime:3.2.1
  #   ports:
  #     - "${LEANTIME_PORT}:80"
  #   restart: unless-stopped
  #   environment:
  #     - LEAN_DB_HOST=leantime_db
  #     - LEAN_DB_USER=leantime
  #     - LEAN_DB_PASSWORD=${LEANTIME_DB_PASSWORD}
  #     - LEAN_DB_DATABASE=leantime
  #     - LEAN_DB_PORT=3306
  #     - LEAN_APP_URL=https://${PUBLIC_URL_LEANTIME}
  #     - LEAN_DEBUG=1
  #     - LEAN_APP_DIR=""
  #     - LEAN_PORT=1212
  #   networks:
  #     - web
  #     - default
  #   volumes:
  #     - ../data/leantime/public_userfiles:/var/www/html/public/userfiles
  #     - ../data/leantime/userfiles:/var/www/html/userfiles
  #     - ../data/leantime/plugins:/var/www/html/app/Plugins
  #   depends_on:
  #     - leantime_db
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=web"
  #     - "traefik.http.routers.leantime.rule=Host(`${PUBLIC_URL_LEANTIME}`) || Host(`leantime.lan`)"
  #     - "traefik.http.routers.leantime.entrypoints=websecure"
  #     - "traefik.http.routers.leantime.tls.certResolver=myresolver"
  #     - "homepage.group=Platal"
  #     - "homepage.name=Leantime"
  #     - "homepage.icon=mdi-calendar"
  #     - "homepage.href=https://${PUBLIC_URL_LEANTIME}"
  #     - "homepage.description=Project management"

  # leantime_db:
  #   image: mysql:8.4
  #   volumes:
  #     - ../data/leantime/mysql:/var/lib/mysql
  #   restart: unless-stopped
  #   command: --character-set-server=UTF8MB4 --collation-server=UTF8MB4_unicode_ci
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${LEANTIME_MYSQL_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=leantime
  #     - MYSQL_USER=leantime
  #     - MYSQL_PASSWORD=${LEANTIME_DB_PASSWORD}
  #   healthcheck:
  #     test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD" ]
  #     interval: 2s
  #     retries: 5
  #     start_period: 30s

  # openproject:
  #   image: openproject/openproject:14
  #   environment:
  #     - OPENPROJECT_HOST__NAME=${PUBLIC_URL_OPENPROJECT}
  #     - OPENPROJECT_SECRET_KEY_BASE=${OPENPROJECT_SECRET_KEY_BASE}
  #     - OPENPROJECT_HTTPS=true
  #   ports:
  #     - "${OPENPROJECT_PORT}:80"
  #   restart: unless-stopped
  #   volumes:
  #     - ../data/openproject/pgdata:/var/openproject/pgdata
  #     - ../data/openproject/assets:/var/openproject/assets
  #   networks:
  #     - web
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=web"
  #     - "traefik.http.routers.openproject.rule=Host(`${PUBLIC_URL_OPENPROJECT}`) || Host(`openproject.lan`)"
  #     - "traefik.http.routers.openproject.entrypoints=websecure"
  #     - "traefik.http.routers.openproject.tls.certResolver=myresolver"
  #     - "homepage.group=Platal"
  #     - "homepage.name=OpenProject"
  #     - "homepage.icon=mdi-calendar"
  #     - - "homepage.href=https://${PUBLIC_URL_OPENPROJECT}"
  #     - "homepage.description=Project management"

networks:
  web:
    external: true
